name: STEERERV
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=2.0.5
  - backcall=0.2.0
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.7.2
  - certifi=2024.7.4
  - charset-normalizer=2.0.4
  - cudatoolkit=11.3.1
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - ffmpeg=4.3
  - freetype=2.12.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - idna=3.7
  - intel-openmp=2023.1.0
  - ipython=8.15.0
  - jedi=0.19.1
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libdeflate=1.17
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - ncurses=6.4
  - nettle=3.7.3
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.0.14
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.3.0
  - pip=24.0
  - prompt-toolkit=3.0.43
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.15.1
  - pysocks=1.7.1
  - python=3.9.19
  - pytorch=1.12.0
  - pytorch-mutex=1.0
  - readline=8.2
  - requests=2.32.2
  - setuptools=69.5.1
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.2.0
  - tbb=2021.8.0
  - tk=8.6.14
  - torchvision=0.13.0
  - traitlets=5.14.3
  - typing_extensions=4.11.0
  - urllib3=2.2.2
  - wcwidth=0.2.5
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - addict==2.4.0
      - contourpy==1.3.0
      - cycler==0.12.1
      - dict-recursive-update==1.0.1
      - einops==0.8.0
      - filelock==3.15.4
      - fonttools==4.53.1
      - fsspec==2024.6.1
      - fvcore==0.1.5.post20221221
      - huggingface-hub==0.23.4
      - importlib-metadata==8.0.0
      - importlib-resources==6.4.4
      - iopath==0.1.10
      - jinja2==3.1.4
      - kiwisolver==1.4.5
      - markupsafe==2.1.5
      - matplotlib==3.9.2
      - mmcv==1.6.0
      - opencv-python==4.10.0.84
      - packaging==24.1
      - pandas==2.2.2
      - platformdirs==4.2.2
      - portalocker==2.10.0
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - pyyaml==6.0.2
      - safetensors==0.4.3
      - scipy==1.13.1
      - sentry-sdk==2.7.1
      - setproctitle==1.3.3
      - sk-video==1.1.10
      - smmap==5.0.1
      - tabulate==0.9.0
      - tensorboardx==2.6.2
      - timm==1.0.7
      - tqdm==4.66.4
      - trimesh==4.5.2
      - tzdata==2024.1
      - yacs==0.1.8
      - yapf==0.40.2
      - zipp==3.20.1
